# Generated by Django 5.0.6 on 2024-06-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uses_title', models.CharField(max_length=30)),
                ('uses_des', models.CharField(max_length=70)),
            ],
        ),
    ]
