# Generated by Django 5.0.6 on 2024-06-08 08:16

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uses',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='uses_des', unique=True),
        ),
        migrations.AlterField(
            model_name='uses',
            name='uses_des',
            field=models.CharField(max_length=500),
        ),
    ]
