# Generated by Django 5.0.6 on 2024-06-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_uses_slug_alter_uses_uses_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='formData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=80)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='uses',
            name='slug',
        ),
    ]
