# Generated by Django 5.0.6 on 2024-06-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_formdata_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='pics',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='onkar_pics/'),
        ),
    ]
